# ============================================================
# SOURCE DE DONNÉES GRAFANA — Connexion à Prometheus
# ============================================================

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090    # URL interne Docker
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
